flip_camera_topic: "/gopro_5/gopro_out"
test_flip_camera_topic: "/flip_camera/test"

path_rgb_camera_topic: "/zed/zed_node/stereo/image_rect_color"
path_depth_camera_topic: "/zed/zed_node/point_cloud/cloud_registered"
test_path_camera_topic: "/path_camera/test"

flip_pos_topic: "/boat_controller/flip/flip_pos"
path_pos_topic: "/boat_controller/path/path_pos"

mode_topic: "/boat_controller/mode"

dilation: 2
thres_area_prop: 0.05
shear_factor: 100

camera_height: 1
tl: [120,80]
br: [432, 240]
vertical: 1
direction: 1
area_prop: 0.5

width: 432
height: 240

side: 1.0
