flip_camera_topic: "/flip_camera/image_bag_raw"
test_flip_camera_topic: "/flip_camera/test"

path_camera_topic: "/path_camera/image_bag_raw"
test_path_camera_topic: "/path_camera/test"

flip_pos_topic: "/boat_controller/flip_pos"
path_pos_topic: "/boat_controller/path_pos"

lower_color_range: [140,130,60]
upper_color_range: [190,255,255]
flip_area: 250

tr: [[160, 40 ], [240, 200]]
tl: [[80 , 40 ], [160, 200]]
br: [[160, 280], [240, 440]]
bl: [[80 , 280], [160, 440]]
width: 640
height: 480

side: 1.0
